package com.my.common.dao;

import com.my.common.model.SysAuthorities;
import com.my.common.model.SysAuthoritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    int countByExample(SysAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    int deleteByExample(SysAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    int insert(SysAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    int insertSelective(SysAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    List<SysAuthorities> selectByExample(SysAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysAuthorities record, @Param("example") SysAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authorities
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    int updateByExample(@Param("record") SysAuthorities record, @Param("example") SysAuthoritiesExample example);
}