package com.my.common.dao;

import com.my.common.model.SysModules;
import com.my.common.model.SysModulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysModulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int countByExample(SysModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int deleteByExample(SysModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int deleteByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int insert(SysModules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int insertSelective(SysModules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    List<SysModules> selectByExample(SysModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    SysModules selectByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysModules record, @Param("example") SysModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int updateByExample(@Param("record") SysModules record, @Param("example") SysModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int updateByPrimaryKeySelective(SysModules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_modules
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    int updateByPrimaryKey(SysModules record);
}