package com.my.common.dao;

import com.my.common.model.SysResources;
import com.my.common.model.SysResourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int countByExample(SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int deleteByExample(SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int insert(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int insertSelective(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    List<SysResources> selectByExample(SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    SysResources selectByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysResources record, @Param("example") SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int updateByExample(@Param("record") SysResources record, @Param("example") SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int updateByPrimaryKeySelective(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    int updateByPrimaryKey(SysResources record);
}