package com.my.common.dao;

import com.my.common.model.SysStyles;
import com.my.common.model.SysStylesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysStylesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int countByExample(SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int deleteByExample(SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int deleteByPrimaryKey(String styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int insert(SysStyles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int insertSelective(SysStyles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    List<SysStyles> selectByExample(SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    SysStyles selectByPrimaryKey(String styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysStyles record, @Param("example") SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int updateByExample(@Param("record") SysStyles record, @Param("example") SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int updateByPrimaryKeySelective(SysStyles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Sat Feb 07 09:41:02 CST 2015
     */
    int updateByPrimaryKey(SysStyles record);
}