package com.my.common.model;

public class SysAuthorities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.AUTHORITY_ID
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.AUTHORITY_MARK
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String authorityMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.AUTHORITY_NAME
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String authorityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.AUTHORITY_DESC
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String authorityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.MESSAGE
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.IS_SYS
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authorities.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.AUTHORITY_ID
     *
     * @return the value of sys_authorities.AUTHORITY_ID
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.AUTHORITY_ID
     *
     * @param authorityId the value for sys_authorities.AUTHORITY_ID
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.AUTHORITY_MARK
     *
     * @return the value of sys_authorities.AUTHORITY_MARK
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getAuthorityMark() {
        return authorityMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.AUTHORITY_MARK
     *
     * @param authorityMark the value for sys_authorities.AUTHORITY_MARK
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setAuthorityMark(String authorityMark) {
        this.authorityMark = authorityMark == null ? null : authorityMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.AUTHORITY_NAME
     *
     * @return the value of sys_authorities.AUTHORITY_NAME
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.AUTHORITY_NAME
     *
     * @param authorityName the value for sys_authorities.AUTHORITY_NAME
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.AUTHORITY_DESC
     *
     * @return the value of sys_authorities.AUTHORITY_DESC
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getAuthorityDesc() {
        return authorityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.AUTHORITY_DESC
     *
     * @param authorityDesc the value for sys_authorities.AUTHORITY_DESC
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setAuthorityDesc(String authorityDesc) {
        this.authorityDesc = authorityDesc == null ? null : authorityDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.MESSAGE
     *
     * @return the value of sys_authorities.MESSAGE
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.MESSAGE
     *
     * @param message the value for sys_authorities.MESSAGE
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.ENABLED
     *
     * @return the value of sys_authorities.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.ENABLED
     *
     * @param enabled the value for sys_authorities.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.IS_SYS
     *
     * @return the value of sys_authorities.IS_SYS
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.IS_SYS
     *
     * @param isSys the value for sys_authorities.IS_SYS
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys == null ? null : isSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authorities.MODULE_ID
     *
     * @return the value of sys_authorities.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authorities.MODULE_ID
     *
     * @param moduleId the value for sys_authorities.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:21:35 CST 2015
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}