package com.my.common.model;

public class SysModules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.MODULE_NAME
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.MODULE_DESC
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String moduleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.MODULE_TYPE
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.PARENT
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.MODULE_URL
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.LEVEL
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.LEAF
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.APPLICATION
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String application;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.CONTROLLER
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String controller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_modules.PRIORITY
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.MODULE_ID
     *
     * @return the value of sys_modules.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.MODULE_ID
     *
     * @param moduleId the value for sys_modules.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.MODULE_NAME
     *
     * @return the value of sys_modules.MODULE_NAME
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.MODULE_NAME
     *
     * @param moduleName the value for sys_modules.MODULE_NAME
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.MODULE_DESC
     *
     * @return the value of sys_modules.MODULE_DESC
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.MODULE_DESC
     *
     * @param moduleDesc the value for sys_modules.MODULE_DESC
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc == null ? null : moduleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.MODULE_TYPE
     *
     * @return the value of sys_modules.MODULE_TYPE
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.MODULE_TYPE
     *
     * @param moduleType the value for sys_modules.MODULE_TYPE
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType == null ? null : moduleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.PARENT
     *
     * @return the value of sys_modules.PARENT
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.PARENT
     *
     * @param parent the value for sys_modules.PARENT
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.MODULE_URL
     *
     * @return the value of sys_modules.MODULE_URL
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.MODULE_URL
     *
     * @param moduleUrl the value for sys_modules.MODULE_URL
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.LEVEL
     *
     * @return the value of sys_modules.LEVEL
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.LEVEL
     *
     * @param level the value for sys_modules.LEVEL
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.LEAF
     *
     * @return the value of sys_modules.LEAF
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.LEAF
     *
     * @param leaf the value for sys_modules.LEAF
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setLeaf(String leaf) {
        this.leaf = leaf == null ? null : leaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.APPLICATION
     *
     * @return the value of sys_modules.APPLICATION
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.APPLICATION
     *
     * @param application the value for sys_modules.APPLICATION
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setApplication(String application) {
        this.application = application == null ? null : application.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.CONTROLLER
     *
     * @return the value of sys_modules.CONTROLLER
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getController() {
        return controller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.CONTROLLER
     *
     * @param controller the value for sys_modules.CONTROLLER
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setController(String controller) {
        this.controller = controller == null ? null : controller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.ENABLED
     *
     * @return the value of sys_modules.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.ENABLED
     *
     * @param enabled the value for sys_modules.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_modules.PRIORITY
     *
     * @return the value of sys_modules.PRIORITY
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_modules.PRIORITY
     *
     * @param priority the value for sys_modules.PRIORITY
     *
     * @mbggenerated Sat Jan 10 22:22:21 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}