package com.my.common.model;

public class SysRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_ID
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_NAME
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ROLE_DESC
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.IS_SYS
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    private String isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_ID
     *
     * @return the value of sys_roles.ROLE_ID
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_ID
     *
     * @param roleId the value for sys_roles.ROLE_ID
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_NAME
     *
     * @return the value of sys_roles.ROLE_NAME
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_NAME
     *
     * @param roleName the value for sys_roles.ROLE_NAME
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ROLE_DESC
     *
     * @return the value of sys_roles.ROLE_DESC
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ROLE_DESC
     *
     * @param roleDesc the value for sys_roles.ROLE_DESC
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ENABLED
     *
     * @return the value of sys_roles.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ENABLED
     *
     * @param enabled the value for sys_roles.ENABLED
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.IS_SYS
     *
     * @return the value of sys_roles.IS_SYS
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.IS_SYS
     *
     * @param isSys the value for sys_roles.IS_SYS
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys == null ? null : isSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.MODULE_ID
     *
     * @return the value of sys_roles.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.MODULE_ID
     *
     * @param moduleId the value for sys_roles.MODULE_ID
     *
     * @mbggenerated Sat Jan 10 22:23:23 CST 2015
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}