package com.my.common.model;

public class SysResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_NAME
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_DESC
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.RESOURCE_PATH
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String resourcePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.PARENT_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.PRIORITY
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.ENABLED
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.IS_SYS
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.MODULE_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_ID
     *
     * @return the value of sys_resources.RESOURCE_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_ID
     *
     * @param resourceId the value for sys_resources.RESOURCE_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_TYPE
     *
     * @return the value of sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_TYPE
     *
     * @param resourceType the value for sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_NAME
     *
     * @return the value of sys_resources.RESOURCE_NAME
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_NAME
     *
     * @param resourceName the value for sys_resources.RESOURCE_NAME
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_DESC
     *
     * @return the value of sys_resources.RESOURCE_DESC
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_DESC
     *
     * @param resourceDesc the value for sys_resources.RESOURCE_DESC
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc == null ? null : resourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.RESOURCE_PATH
     *
     * @return the value of sys_resources.RESOURCE_PATH
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.RESOURCE_PATH
     *
     * @param resourcePath the value for sys_resources.RESOURCE_PATH
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setResourcePath(String resourcePath) {
        this.resourcePath = resourcePath == null ? null : resourcePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.PARENT_ID
     *
     * @return the value of sys_resources.PARENT_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.PARENT_ID
     *
     * @param parentId the value for sys_resources.PARENT_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.PRIORITY
     *
     * @return the value of sys_resources.PRIORITY
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.PRIORITY
     *
     * @param priority the value for sys_resources.PRIORITY
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.ENABLED
     *
     * @return the value of sys_resources.ENABLED
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.ENABLED
     *
     * @param enabled the value for sys_resources.ENABLED
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.IS_SYS
     *
     * @return the value of sys_resources.IS_SYS
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.IS_SYS
     *
     * @param isSys the value for sys_resources.IS_SYS
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys == null ? null : isSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.MODULE_ID
     *
     * @return the value of sys_resources.MODULE_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.MODULE_ID
     *
     * @param moduleId the value for sys_resources.MODULE_ID
     *
     * @mbggenerated Fri Feb 06 23:55:33 CST 2015
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}