package com.my.common.model;

public class SysStyles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_ID
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    private String styleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_NAME
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    private String styleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_DESC
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    private String styleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_NAME
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    private String iconName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_DESC
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    private String iconDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.REMARK
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_ID
     *
     * @return the value of sys_styles.STYLE_ID
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public String getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_ID
     *
     * @param styleId the value for sys_styles.STYLE_ID
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public void setStyleId(String styleId) {
        this.styleId = styleId == null ? null : styleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_NAME
     *
     * @return the value of sys_styles.STYLE_NAME
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public String getStyleName() {
        return styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_NAME
     *
     * @param styleName the value for sys_styles.STYLE_NAME
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public void setStyleName(String styleName) {
        this.styleName = styleName == null ? null : styleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_DESC
     *
     * @return the value of sys_styles.STYLE_DESC
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public String getStyleDesc() {
        return styleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_DESC
     *
     * @param styleDesc the value for sys_styles.STYLE_DESC
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public void setStyleDesc(String styleDesc) {
        this.styleDesc = styleDesc == null ? null : styleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_NAME
     *
     * @return the value of sys_styles.ICON_NAME
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_NAME
     *
     * @param iconName the value for sys_styles.ICON_NAME
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public void setIconName(String iconName) {
        this.iconName = iconName == null ? null : iconName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_DESC
     *
     * @return the value of sys_styles.ICON_DESC
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public String getIconDesc() {
        return iconDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_DESC
     *
     * @param iconDesc the value for sys_styles.ICON_DESC
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public void setIconDesc(String iconDesc) {
        this.iconDesc = iconDesc == null ? null : iconDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.REMARK
     *
     * @return the value of sys_styles.REMARK
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.REMARK
     *
     * @param remark the value for sys_styles.REMARK
     *
     * @mbggenerated Thu Feb 05 22:10:43 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}